CREATE TABLE MENU
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ITEM_NAME NVARCHAR2(255) NOT NULL,
  SMALL_SIZE_PRICE NUMERIC(5, 2) NOT NULL,
  DESCRIPTION NVARCHAR2(500),
  ITEM_IMAGE NVARCHAR2(50)
);


CREATE TABLE SIZE_CATEGORY
(
  ID SMALLINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ITEM_SIZE NUMERIC(4, 2) NOT NULL,
  MARKUP NUMERIC(4, 2) NOT NULL
);

CREATE TABLE MENU_ITEM_INFO
(
   ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
   MENU_ITEM_ID INT NOT NULL,
   MENU_ITEM_SIZE SMALLINT NOT NULL,
   CONSTRAINT FK_MENU_ITEM_INFO_MENU FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU (ID) ON DELETE CASCADE,
   CONSTRAINT FK_MENU_II_SIZE_CATEGORY FOREIGN KEY (MENU_ITEM_SIZE) REFERENCES SIZE_CATEGORY (ID)
);

CREATE TABLE USER_ROLE
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ROLE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PERSONAL_DATA
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  FULL_NAME NVARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(70) UNIQUE NOT NULL,
  PHONE_NUMBER VARCHAR2(30) UNIQUE NOT NULL,
  DATE_OF_BIRTH DATE
);

CREATE TABLE APP_USER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PASSWORD_HASH NVARCHAR2(300) NOT NULL,
    USER_ROLE INT NOT NULL,
    PERSONAL_DATA INT NOT NULL,
    CONSTRAINT FK_APP_USER_USER_ROLE FOREIGN KEY (USER_ROLE) REFERENCES USER_ROLE (ID),
    CONSTRAINT FK_APP_USER_PERSONAL_DATA FOREIGN KEY (PERSONAL_DATA) REFERENCES PERSONAL_DATA (ID)
);


CREATE TABLE CART
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  CONSTRAINT FK_CART_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
);

CREATE TABLE CART_ITEM
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CART_ID INT NOT NULL,
    ITEM_INFO INT NOT NULL,
    ITEM_QUANTITY INT NOT NULL,
    CONSTRAINT FK_CART_MENU_ITEM_INFO FOREIGN KEY (ITEM_INFO) REFERENCES MENU_ITEM_INFO (ID) ON DELETE CASCADE
);

CREATE TABLE RESTAURANT
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ADDRESS NVARCHAR2(50) UNIQUE NOT NULL,
  LOCATION SDO_GEOMETRY NOT NULL,
  COVERAGE_AREA SDO_GEOMETRY NOT NULL,
  RESTAURANT_ADMIN INT UNIQUE NOT NULL,
  OPEN_TIME TIMESTAMP NOT NULL,
  CLOSE_TIME TIMESTAMP NOT NULL,
  DELIVERY_START_TIME TIMESTAMP NOT NULL,
  DELIVERY_END_TIME TIMESTAMP NOT NULL,
  CONSTRAINT FK_RESTAURANT_APP_USER FOREIGN KEY (RESTAURANT_ADMIN) REFERENCES APP_USER (ID)
);


CREATE TABLE COURIER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PERSONAL_DATA INT NOT NULL,
    SALARY NUMERIC(8, 2) NOT NULL,
    RESTAURANT INT NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    READY_TO_GO NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_COURIER_RESTAURANT FOREIGN KEY (RESTAURANT) REFERENCES RESTAURANT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_COURIER_PERSONAL_DATA FOREIGN KEY (PERSONAL_DATA) REFERENCES PERSONAL_DATA (ID) ON DELETE CASCADE
);

CREATE TABLE USER_ORDER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    DATE_OF_ORDER DATE NOT NULL,
    USER_ID INT NOT NULL,
    ADDRESS NVARCHAR2(60) NOT NULL,
    COURIER_ID INT NOT NULL,
    CONSTRAINT FK_USER_ORDER_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT FK_USER_ORDER_COURIER FOREIGN KEY (COURIER_ID) REFERENCES COURIER (ID) ON DELETE CASCADE
);


CREATE TABLE ORDER_ITEM
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    ITEM_INFO INT NOT NULL,
    ITEM_QUANTITY INT NOT NULL,
    CONSTRAINT FK_ORDER_ITEM_USER_ORDER FOREIGN KEY (ORDER_ID) REFERENCES USER_ORDER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_MENU_ITEM_INFO FOREIGN KEY (ITEM_INFO) REFERENCES MENU_ITEM_INFO (ID) ON DELETE CASCADE
);


-- DROP TABLE ORDER_ITEM;
-- DROP TABLE USER_ORDER;
-- DROP TABLE COURIER;
-- DROP TABLE RESTAURANT;
-- DROP TABLE CART_ITEM;
-- DROP TABLE CART;
-- DROP TABLE APP_USER;
-- DROP TABLE USER_ROLE;
-- DROP TABLE PERSONAL_DATA;
-- DROP TABLE MENU_ITEM_INFO;
-- DROP TABLE SIZE_CATEGORY;
-- DROP TABLE MENU;



