BEGIN
    FOR i IN 1..100000
        LOOP
            HEAD_ADMIN_PACKAGE.INSERT_MENU_ITEM('testitem' || i, DBMS_RANDOM.VALUE(10, 25), 'test_desc' || i, '\images\1696149010415-italian.webp');
        END LOOP;
END;



EXPLAIN PLAN FOR SELECT * FROM MENU WHERE ITEM_NAME = 'Пепперони';
EXPLAIN PLAN FOR SELECT * FROM MENU WHERE SMALL_SIZE_PRICE < 10;
EXPLAIN PLAN FOR SELECT SMALL_SIZE_PRICE, COUNT(*) FROM MENU GROUP BY SMALL_SIZE_PRICE;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(format => 'ALL'));



SELECT COUNT(ID)
from GET_PRODUCTS;

SELECT * from GET_PRODUCTS
WHERE ITEM_NAME = 'testitem';