CREATE OR REPLACE TRIGGER CHECK_MENU_ITEM_PRICE
    BEFORE INSERT
    ON MENU
    FOR EACH ROW
BEGIN
    IF :NEW.SMALL_SIZE_PRICE <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Цена товара должна быть положительной.');
    END IF;
END;

CREATE OR REPLACE TRIGGER CHECK_SIZE_CATEGORY_VALUES
    BEFORE INSERT
    ON SIZE_CATEGORY
    FOR EACH ROW
BEGIN
    IF :NEW.ITEM_SIZE <= 0 OR :NEW.MARKUP <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Значения ITEM_SIZE и MARKUP должны быть положительными числами.');
    END IF;
END;


CREATE OR REPLACE TRIGGER TRG_UPDATE_READY_TO_GO
    BEFORE UPDATE
    ON COURIER
    FOR EACH ROW
BEGIN
    IF :OLD.ACTIVE = 1 AND :NEW.ACTIVE = 0 THEN
        :NEW.READY_TO_GO := 0;
    END IF;
END;

CREATE OR REPLACE TRIGGER TRG_CHECK_SALARY
    BEFORE INSERT OR UPDATE
    ON COURIER
    FOR EACH ROW
BEGIN
    IF :NEW.SALARY <= 0 THEN
        RAISE_APPLICATION_ERROR('-20001', 'Зарплата должна быть больше нуля.');
    END IF;
END;





