CREATE OR REPLACE TYPE RECORD_RESTAURANT AS OBJECT
(
    ID                  INT,
    ADDRESS             NVARCHAR2(50),
    LOCATION            CLOB,
    COVERAGE_AREA       CLOB,
    RESTAURANT_ADMIN    INT,
    OPEN_TIME           VARCHAR2(20),
    CLOSE_TIME          VARCHAR2(20),
    DELIVERY_START_TIME VARCHAR2(20),
    DELIVERY_END_TIME   VARCHAR2(20)
);

CREATE OR REPLACE TYPE TABLE_RESTAURANT AS TABLE OF RECORD_RESTAURANT;

CREATE OR REPLACE TYPE RECORD_MENU AS OBJECT
(
    ID               INT,
    ITEM_NAME        NVARCHAR2(255),
    SMALL_SIZE_PRICE NUMERIC(5, 2),
    DESCRIPTION      NVARCHAR2(500),
    ITEM_IMAGE       NVARCHAR2(50)
);


CREATE OR REPLACE TYPE TABLE_MENU AS TABLE OF RECORD_MENU;


CREATE OR REPLACE TYPE RECORD_COURIER AS OBJECT
(
    ID            INT,
    FULL_NAME     NVARCHAR2(100),
    EMAIL         VARCHAR2(70),
    PHONE_NUMBER  VARCHAR2(30),
    DATE_OF_BIRTH VARCHAR2(10),
    SALARY        NUMERIC(8, 2),
    ACTIVE        NUMBER(1),
    READY_TO_GO   NUMBER(1)
);

CREATE OR REPLACE TYPE TABLE_COURIER AS TABLE OF RECORD_COURIER;


CREATE OR REPLACE TYPE RECORD_CART_ITEM AS OBJECT
(
    CART_ID       INT,
    ITEM_ID       INT,
    USER_ID       INT,
    MENU_ITEM_ID  INT,
    ITEM_SIZE     NUMERIC(4, 2),
    MARKUP        NUMERIC(4, 2),
    ITEM_QUANTITY SMALLINT
);


CREATE OR REPLACE TYPE TABLE_CART_ITEM AS TABLE OF RECORD_CART_ITEM;


CREATE OR REPLACE TYPE RECORD_ORDER AS OBJECT
(    ID            INT,
    DATE_OF_ORDER VARCHAR2(50),
    USER_ID       INT,
    ADDRESS NVARCHAR2(60)
);


CREATE OR REPLACE TYPE TABLE_ORDER AS TABLE OF RECORD_ORDER;


CREATE OR REPLACE TYPE RECORD_ORDER_ITEM AS OBJECT
(
    ID            INT,
    MENU_ITEM_ID  INT,
    ITEM_SIZE     NUMERIC(4, 2),
    MARKUP        NUMERIC(4, 2),
    ITEM_QUANTITY SMALLINT
);

CREATE OR REPLACE TYPE TABLE_ORDER_ITEM AS TABLE OF RECORD_ORDER_ITEM;


CREATE OR REPLACE TYPE RECORD_ORDER_REST AS OBJECT
(
    ID            INT,
    DATE_OF_ORDER VARCHAR2(50),
    PHONE_NUMBER  VARCHAR2(30),
        ADDRESS NVARCHAR2(60)
);

CREATE OR REPLACE TYPE TABLE_ORDER_REST AS TABLE OF RECORD_ORDER_REST;



-- DROP TYPE TABLE_RESTAURANT;
-- DROP TYPE TABLE_MENU;
-- DROP TYPE TABLE_COURIER;
-- DROP TYPE TABLE_CART_ITEM;
-- DROP TYPE TABLE_ORDER;
-- DROP TYPE TABLE_ORDER_ITEM;
-- DROP TYPE TABLE_ORDER_REST;
--
-- DROP TYPE RECORD_ORDER_REST;
-- DROP TYPE RECORD_ORDER_ITEM;
-- DROP TYPE RECORD_ORDER;
-- DROP TYPE RECORD_CART_ITEM;
-- DROP TYPE RECORD_COURIER;
-- DROP TYPE RECORD_MENU;
-- DROP TYPE RECORD_RESTAURANT;