-- HEAD ADMIN
CREATE ROLE HEAD_ADMIN_ROLE;
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE PROFILE,
    CREATE USER,
    DROP USER,
    CREATE ROLE,
    DROP PROFILE,
    CREATE TRIGGER,
    DROP ANY TRIGGER,
    CREATE ANY INDEX,
    CREATE TYPE,
    DROP ANY TYPE,
    EXECUTE ANY INDEXTYPE,
    CREATE ANY SEQUENCE
    TO HEAD_ADMIN_ROLE WITH ADMIN OPTION;


CREATE PROFILE HEAD_ADMIN_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 10
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

ALTER USER HEAD_ADMIN PROFILE HEAD_ADMIN_PROFILE;
ALTER USER HEAD_ADMIN DEFAULT TABLESPACE RESTAURANT_TS QUOTA UNLIMITED ON RESTAURANT_TS;
ALTER USER HEAD_ADMIN TEMPORARY TABLESPACE RESTAURANT_TS_TEMP;
GRANT HEAD_ADMIN_ROLE TO HEAD_ADMIN;

-- Пользовательский профиль

CREATE PROFILE USERS_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 3
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 60;

-- Роль - базовый доступ к представлениям
CREATE ROLE BASE_ROLE;

GRANT EXECUTE ON HEAD_ADMIN.USER_PACKAGE TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_PRODUCTS TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_ORDER_ITEMS TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_PRICES TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_ORDERS_INFO TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_CART_INFO TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_RESTAURANTS_INFO TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_USERS TO BASE_ROLE;

-- Роль - покупатель

CREATE USER CUSTOMER
    IDENTIFIED BY qwerty12345
    PROFILE USERS_PROFILE;

GRANT CREATE SESSION TO CUSTOMER;
GRANT BASE_ROLE TO CUSTOMER;

-- Роль - администратор ресторана
CREATE ROLE REST_ADMIN_ROLE;
GRANT CREATE SESSION TO REST_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.REST_ADMIN_PACKAGE TO REST_ADMIN_ROLE;

GRANT SELECT ON HEAD_ADMIN.GET_ALL_COURIERS TO REST_ADMIN_ROLE;

CREATE USER REST_ADMIN
    IDENTIFIED BY qwerty12345
    PROFILE USERS_PROFILE;

GRANT BASE_ROLE TO REST_ADMIN;
GRANT REST_ADMIN_ROLE TO REST_ADMIN;
