
CREATE OR REPLACE VIEW GET_USERS AS
SELECT APP_USER.ID, FULL_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, ROLE_NAME, PASSWORD_HASH
FROM APP_USER
         JOIN PERSONAL_DATA PD ON APP_USER.PERSONAL_DATA = PD.ID
         JOIN USER_ROLE UR ON APP_USER.USER_ROLE = UR.ID;

CREATE OR REPLACE VIEW GET_RESTAURANTS AS
SELECT RESTAURANT.ID,
       SDO_UTIL.TO_GEOJSON(LOCATION)      AS LOCATION,
       SDO_UTIL.TO_GEOJSON(COVERAGE_AREA) AS COVERAGE_AREA,
       FULL_NAME
FROM RESTAURANT
         JOIN GET_USERS APP_USER ON RESTAURANT.RESTAURANT_ADMIN = APP_USER.ID;

CREATE OR REPLACE VIEW GET_RESTAURANTS_INFO AS
SELECT RESTAURANT.ID,
       ADDRESS,
       TO_CHAR(OPEN_TIME, 'HH24:MI')           AS OPEN_TIME,
       TO_CHAR(CLOSE_TIME, 'HH24:MI')          AS CLOSE_TIME,
       TO_CHAR(DELIVERY_START_TIME, 'HH24:MI') AS DELIVERY_START_TIME,
       TO_CHAR(DELIVERY_END_TIME, 'HH24:MI')   AS DELIVERY_END_TIME,
       SDO_UTIL.TO_GEOJSON(LOCATION)           AS LOCATION,
       SDO_UTIL.TO_GEOJSON(COVERAGE_AREA)      AS COVERAGE_AREA,
       FULL_NAME                               AS ADMIN
FROM RESTAURANT
         JOIN APP_USER AU ON RESTAURANT.RESTAURANT_ADMIN = AU.ID
         JOIN PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID;


CREATE OR REPLACE VIEW GET_PRODUCTS AS
SELECT *
FROM MENU;

CREATE OR REPLACE VIEW GET_PRICES AS
SELECT *
FROM SIZE_CATEGORY;

CREATE OR REPLACE VIEW ADMIN_USERS AS
SELECT AU.ID,
       PD.FULL_NAME,
       PD.EMAIL,
       PD.PHONE_NUMBER,
       TO_CHAR(PD.DATE_OF_BIRTH, 'DD-MM-YYYY') AS DATE_OF_BIRTH,
       R.ADDRESS
FROM APP_USER AU
         JOIN
     PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID
         JOIN
     USER_ROLE UR ON AU.USER_ROLE = UR.ID
         FULL JOIN
     RESTAURANT R ON AU.ID = R.RESTAURANT_ADMIN
WHERE UR.ROLE_NAME = 'restaurant_admin'
ORDER BY FULL_NAME;

CREATE OR REPLACE VIEW UNASSIGNED_ADMINS AS
SELECT ID,
       FULL_NAME
FROM ADMIN_USERS
WHERE ADDRESS IS NULL;

CREATE OR REPLACE VIEW GET_ALL_COURIERS AS
SELECT COURIER.ID, FULL_NAME, ACTIVE, READY_TO_GO, ADDRESS
FROM COURIER
         JOIN PERSONAL_DATA PD ON PD.ID = COURIER.PERSONAL_DATA
         JOIN RESTAURANT R ON R.ID = COURIER.RESTAURANT;


CREATE OR REPLACE VIEW GET_CART_INFO AS
SELECT CART.ID AS CART_ID, CI.ID AS ITEM_ID, USER_ID, MENU_ITEM_ID, ITEM_SIZE, MARKUP, ITEM_QUANTITY
FROM CART
         INNER JOIN CART_ITEM CI ON CART.ID = CI.CART_ID
         INNER JOIN MENU_ITEM_INFO MII ON MII.ID = CI.ITEM_INFO
         INNER JOIN SIZE_CATEGORY SC ON SC.ID = MII.MENU_ITEM_SIZE;


CREATE OR REPLACE VIEW GET_ORDERS_INFO AS
SELECT USER_ORDER.ID, TO_CHAR(DATE_OF_ORDER, 'DD-MM-YYYY HH24:MI') AS DATE_OF_ORDER, USER_ORDER.ADDRESS, USER_ORDER.USER_ID, PHONE_NUMBER, R.ID AS REST_ID
FROM USER_ORDER INNER JOIN COURIER C2 ON C2.ID = USER_ORDER.COURIER_ID
INNER JOIN RESTAURANT R ON R.ID = C2.RESTAURANT
INNER JOIN APP_USER AU ON USER_ORDER.USER_ID = AU.ID
INNER JOIN PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID;


CREATE OR REPLACE VIEW GET_ORDER_ITEMS AS
SELECT ORDER_ID, ORDER_ITEM.ID, MENU_ITEM_ID, ITEM_SIZE, MARKUP, ITEM_QUANTITY
FROM ORDER_ITEM
         INNER JOIN MENU_ITEM_INFO MII ON MII.ID = ORDER_ITEM.ITEM_INFO
         INNER JOIN SIZE_CATEGORY SC ON SC.ID = MII.MENU_ITEM_SIZE;


-- DROP VIEW GET_USERS;
-- DROP VIEW GET_RESTAURANTS;
-- DROP VIEW GET_RESTAURANTS_INFO;
-- DROP VIEW GET_PRODUCTS;
-- DROP VIEW GET_PRICES;
-- DROP VIEW ADMIN_USERS;
-- DROP VIEW UNASSIGNED_ADMINS;
-- DROP VIEW GET_ALL_COURIERS;
-- DROP VIEW GET_CART_INFO;
-- DROP VIEW GET_ORDERS_INFO;
-- DROP VIEW GET_ORDER_ITEMS;
